application: rvytpl
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /oauth2callback
  script: oauth2client/appengine.py

- url: /.*
  script: main.py
